- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: HEAD
  hooks:
    - id: check-ast
    - id: detect-private-key
    - id: detect-aws-credentials
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace
- repo:  git://github.com/psf/black
  rev: HEAD
  hooks:
    - id: black
- repo: local
  hooks:
    - id: filter-cascade-tests
      name: Tests for filter-cascade
      language: system
      entry: python3 -m pytest
      pass_filenames: false
      files: '.py$'
